In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
shopping_data = pd.read_csv('data/processed/shopping_cleaned.csv')

# Required Analytical Questions

## 1. What are the most popular colors by season?
Based on the chart below

In [4]:
shopping_data.pivot_table(values = 'Purchase Amount (USD)', index='Color', columns='Season', aggfunc= 'count' )

Season                Fall  Spring  Summer  Winter
Color
Aubergine               83       2      13     111
Baby blue               16      69      84      21
Black                   84       5       9     124
Brick red               88       7      12     110
Brown                   97       5       3      89
Burnt orange            93       4       5     112
Fuchsia                  3      45      78      18
Lavender                13      55     102       6
Lemon yellow             9      47      98      13
Mauve                   86       5       7      95
Muted mustard yellow    84       8      13      87
Pale peach               9      52      81      15
Periwinkle               9      54      82       8
Ruby Red                90       3       8     107
Terra cotta             91       4      15     101
Turquoise                7      49      74      16
White                   10      63      81      11

In [5]:
color_x_season = shopping_data.pivot_table(values = 'Purchase Amount (USD)', index='Color', columns='Season', aggfunc= 'count' )
print(color_x_season.idxmax())

Season
Fall          Brown
Spring    Baby blue
Summer     Lavender
Winter        Black
dtype: object

## 2. What is the most popular clothing item by season?

In [6]:
shopping_data.pivot_table(values='Purchase Amount (USD)', index='Item Purchased', columns= 'Season', aggfunc='count')

Season          Fall  Spring  Summer  Winter
Item Purchased
Backpack        72.0     NaN     NaN   113.0
Belt            25.0     NaN     NaN     NaN
Boots           51.0     NaN     NaN    83.0
Dress           36.0    74.0   118.0     NaN
Gloves          68.0     NaN     NaN   112.0
Handbag         31.0    78.0   111.0     NaN
Hoodie          58.0     NaN     NaN   105.0
Jacket          47.0     NaN     NaN    87.0
Jeans           46.0     NaN     NaN     NaN
Leggings        58.0     NaN     NaN   118.0
Pajamas         65.0     NaN     NaN   111.0
Running Shoes   25.0    89.0   134.0     NaN
Scarf           56.0     NaN     NaN   101.0
Shorts          31.0    76.0   152.0     NaN
Socks           71.0     NaN     NaN   101.0
Sunglasses      43.0    80.0   135.0     NaN
Sweater         72.0     NaN     NaN   113.0
T-shirt         17.0    80.0   115.0     NaN

## 3. What is the effect of promo codes on the dollar amount of purchases?

In [ ]:
shopping_data.groupby()

## 4. When do users leave a review?