In [6]:
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
shopping_data = pd.read_csv('data/processed/shopping_cleaned.csv')

In [8]:
shopping_data.head()
shopping_data.info()
shopping_data.describe().round(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3158 entries, 0 to 3157
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    3158 non-null   float64
 1   Gender                 3158 non-null   object
 2   Item Purchased         3158 non-null   object
 3   Purchase Amount (USD)  3158 non-null   float64
 4   Location               3158 non-null   object
 5   Size                   3158 non-null   object
 6   Color                  3158 non-null   object
 7   Season                 3158 non-null   object
 8   Review Rating          3158 non-null   object
 9   Shipping Type          3158 non-null   object
 10  Promo Code Used        3158 non-null   object
 11  Previous Purchases     3158 non-null   int64
 12  Payment Method         3158 non-null   object
dtypes: float64(2), int64(1), object(10)
memory usage: 320.9+ KB

           Age  Purchase Amount (USD)  Previous Purchases
count  3158.00                3158.00             3158.00
mean     34.19                  38.81                5.86
std      10.58                  11.53                5.84
min      18.00                  11.95                0.00
25%      26.00                  29.42                1.00
50%      33.00                  37.13                4.00
75%      41.00                  48.97                9.00
max      73.00                  68.33               20.00

# Exploration Questions

## Which payment methods yields the highest amount of purchases overall?
Based on the table below Credit Cards are most used for purchases.

In [9]:
shopping_data.groupby('Payment Method').size().reset_index(name='Count').sort_values(by='Count', ascending=False)

  Payment Method  Count
2    Credit Card   1139
3     Debit Card   1043
4         PayPal    496
5          Venmo    461
0  Bank Transfer     10
1           Cash      9

## Which gender spends more in each season?
During the Fall males spend more, during the Spring and winter non-binary people spend the most. For winter females spend the most. This information is important to understand which items will most likely sell the most during each season.

In [10]:
shopping_data.pivot_table(values='Purchase Amount (USD)', index='Gender', columns='Season', aggfunc='mean').round(2)

Season       Fall  Spring  Summer  Winter
Gender
Female      38.64   39.89   38.98   38.97
Male        39.20   39.00   38.60   37.92
Non-binary  38.43   42.21   33.38   40.15

In [13]:
gender_x_season = shopping_data.pivot_table(values='Purchase Amount (USD)', index='Gender', columns='Season', aggfunc='mean').round(2)
gender_x_season.idxmax()

Season
Fall            Male
Spring    Non-binary
Summer        Female
Winter    Non-binary
dtype: object

## Which age group spends the most in each location?
The chart below displays the average age of spenders in each state. This information allows FlashFash to cater to each age group in each state with intention.

In [23]:
shopping_data.groupby('Location')['Age'].mean().astype(int).reset_index()

          Location  Age
0          Alabama   34
1           Alaska   31
2          Arizona   32
3         Arkansas   37
4       California   34
5         Colorado   35
6      Connecticut   36
7         Delaware   36
8          Florida   33
9          Georgia   32
10          Hawaii   34
11           Idaho   34
12        Illinois   32
13         Indiana   35
14            Iowa   33
15          Kansas   35
16        Kentucky   33
17       Louisiana   34
18           Maine   34
19        Maryland   35
20   Massachusetts   33
21        Michigan   35
22       Minnesota   34
23     Mississippi   35
24        Missouri   34
25         Montana   34
26        Nebraska   36
27          Nevada   34
28   New Hampshire   34
29      New Jersey   33
30      New Mexico   36
31        New York   33
32  North Carolina   33
33    North Dakota   35
34            Ohio   32
35        Oklahoma   33
36          Oregon   33
37    Pennsylvania   30
38    Rhode Island   34
39  South Carolina   33
40    South Dakota   33
41       Tennessee   33
42           Texas   34
43            Utah   33
44         Vermont   32
45        Virginia   32
46      Washington   33
47   West Virginia   33
48       Wisconsin   34
49         Wyoming   31

## Which Shipping Method is most used?
Based on these stats Standard shipping is the most used shipping method. Consumers tend to abandon their online cart once they discover that there is a shipping fee, so this information can help FlashFash come up with a balance between item cost and shipping cost so that the shipping can appear free to the consumer and they are more likely to complete their purchase.

In [26]:
shopping_data.groupby('Shipping Type')['Item Purchased'].size().reset_index().sort_values(by='Item Purchased', ascending=False)

    Shipping Type  Item Purchased
3        Standard            1756
0  2-Day Shipping             953
1         Express             225
2    Next Day Air             223
4    Store Pickup               1