In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
shopping_data = pd.read_csv('data/processed/shopping_cleaned.csv')

In [4]:
shopping_data.head()
shopping_data.info()
shopping_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3158 entries, 0 to 3157
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    3158 non-null   float64
 1   Gender                 3158 non-null   object
 2   Item Purchased         3158 non-null   object
 3   Purchase Amount (USD)  3158 non-null   float64
 4   Location               3158 non-null   object
 5   Size                   3158 non-null   object
 6   Color                  3158 non-null   object
 7   Season                 3158 non-null   object
 8   Review Rating          3158 non-null   object
 9   Shipping Type          3158 non-null   object
 10  Promo Code Used        3158 non-null   object
 11  Previous Purchases     3158 non-null   int64
 12  Payment Method         3158 non-null   object
dtypes: float64(2), int64(1), object(10)
memory usage: 320.9+ KB

               Age  Purchase Amount (USD)  Previous Purchases
count  3158.000000            3158.000000         3158.000000
mean     34.185244              38.812750            5.860988
std      10.578195              11.525595            5.844408
min      18.000000              11.946095            0.000000
25%      26.000000              29.419108            1.000000
50%      33.000000              37.126663            4.000000
75%      41.000000              48.974363            9.000000
max      73.000000              68.327455           20.000000

In [5]:
shopping_data.pivot_table(values = 'Purchase Amount (USD)', index='Color', columns='Season', aggfunc= 'mean' )

Season                     Fall     Spring     Summer     Winter
Color
Aubergine             38.401773  39.081951  38.617332  38.431995
Baby blue             33.809663  40.328704  36.320726  43.589423
Black                 38.125862  36.809507  36.060796  38.374665
Brick red             39.791640  31.688066  40.605329  39.074112
Brown                 39.292763  43.985329  35.672405  36.937905
Burnt orange          40.036616  45.004587  46.148812  37.771428
Fuchsia               49.545995  38.150285  37.565115  40.779632
Lavender              40.932869  38.807579  38.332493  36.574022
Lemon yellow          37.750577  39.543187  39.739865  36.533089
Mauve                 39.038259  36.907834  39.384795  37.672316
Muted mustard yellow  35.951064  42.456599  37.668701  37.825386
Pale peach            43.556007  38.570911  40.667710  40.451551
Periwinkle            39.574759  44.227817  38.958635  40.653097
Ruby Red              40.905482  30.809475  36.785260  38.616632
Terra cotta           38.387880  40.710695  40.458235  40.074474
Turquoise             36.230306  37.858346  39.932830  39.059638
White                 41.234128  38.108058  38.217440  34.340983

## Which payment methods are yields the highest purchase amount overall?

In [6]:
shopping_data.groupby('Payment Method').size().reset_index(name='Count').sort_values(by='Count', ascending=False)

  Payment Method  Count
2    Credit Card   1139
3     Debit Card   1043
4         PayPal    496
5          Venmo    461
0  Bank Transfer     10
1           Cash      9

## Which gender spends more in each season?

In [17]:
shopping_data.pivot_table(values='Purchase Amount (USD)', index='Gender', columns='Season', aggfunc='mean').round(2)

Season       Fall  Spring  Summer  Winter
Gender
Female      38.64   39.89   38.98   38.97
Male        39.20   39.00   38.60   37.92
Non-binary  38.43   42.21   33.38   40.15

## Which age group spends the most in each location?

In [16]:
shopping_data.groupby('Location')['Age'].mean().astype(int)

Location
Alabama           34
Alaska            31
Arizona           32
Arkansas          37
California        34
Colorado          35
Connecticut       36
Delaware          36
Florida           33
Georgia           32
Hawaii            34
Idaho             34
Illinois          32
Indiana           35
Iowa              33
Kansas            35
Kentucky          33
Louisiana         34
Maine             34
Maryland          35
Massachusetts     33
Michigan          35
Minnesota         34
Mississippi       35
Missouri          34
Montana           34
Nebraska          36
Nevada            34
New Hampshire     34
New Jersey        33
New Mexico        36
New York          33
North Carolina    33
North Dakota      35
Ohio              32
Oklahoma          33
Oregon            33
Pennsylvania      30
Rhode Island      34
South Carolina    33
South Dakota      33
Tennessee         33
Texas             34
Utah              33
Vermont           32
Virginia          32
Washington        33
West Virginia     33
Wisconsin         34
Wyoming           31
Name: Age, dtype: int64